import { makeStyles } from "@material-ui/core";
export default makeStyles(theme =>({
    Portforio:{
        width:'90%',
        height:'420px',

        margin:'auto',
        textAlign:'center',
        marginTop:'20px',
        
    },
    img1:{
        width:'99.9%',
        height:'200px',
        borderRadius:'5px',
        objectFit:'cover',
        marginBottom:'10px'
    },
    imgitems:{
        display:'flex',
        alignItems:'center',
        justifyContent:'space-between'
    },
    img2:{
        width:'96%',
        height:'200px',
        borderRadius:'5px',
        objectFit:'contain'
    },
    img3:{
        width:'96%',
        height:'200px',
        borderRadius:'5px',
        objectFit:'contain'
    },
    img4:{
        width:'96%',
        height:'200px',
        borderRadius:'5px',
        objectFit:'contain'
    },
    bestsellerlaptop:{
        width:'90%',
        height:'300px',
        margin:'auto',
        marginTop:'45px',
        border:'1px solid #dbdbdb',
        [theme.breakpoints.down('sm')]:{
            border:'none',
            height:'auto',
            overflowY: 'scroll',
        }
    },
    bestlaptop:{
        width:'100%',
        display:'flex',
        alignItems:'center',
        flexDirection:'column',

    },
    typografy:{
        marginTop:'5px',
        marginRight:'3px'
    },
    text:{
        width:'100%',
        display:'flex',
        justifyContent:'space-between'
    },
    buylaptop:{
        width:'100%',
        height:'250px',
        display:'flex',
        alignItems:'center',
        [theme.breakpoints.down('sm')]:{
            height:'350px',
            flexDirection:'column'
        }
    },
    itemss:{
        width:'23%',
        height:'100%',
        display:'flex',
        alignItems:'center',
        flexDirection:'column',
        marginRight:'5px',
        boxShadow: ' rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px',
        marginRight:'20px',
        [theme.breakpoints.down('sm')]:{
            width:'50%',
            marginTop:'30px'
        }
    },
    imglaptop:{
        width:'98%',
        height:'150px',
        objectFit:'contain',
        [theme.breakpoints.down('sm')]:{
            height:'250px'
        }
    },
    textbuylaptop:{
        width:'100%',
        height:'100%',
        display:'flex',
        alignItems:'center',
        flexDirection:'column',
        backgroundColor:'#888685',
        borderBottomLeftRadius:'10px',
        borderBottomRightRadius:'10px'
    },
    button:{
        fontFamily:'vazir',
        width:'200px',
        backgroundColor:'red',
        color:'#fff'
    },
    banner:{
        width:'100%',
        height:'220px',
        margin:'auto',
        display:'flex',
        alignItems:'center',
        marginTop:'40px',
        position:'relative'
    },
    bannerimg:{
        width:'90%',
        height:'90%',
        margin:'auto',
        objectFit:'contain'
    },
    bestsellermobile:{
        width:'90%',
        height:'300px',
        margin:'auto',
        marginTop:'45px',
        border:'1px solid #dbdbdb',
        [theme.breakpoints.down('sm')]:{
            border:'none',
            height:'auto',
            overflowY: 'scroll',
        }
    },
    buymobile:{
        width:'100%',
        height:'250px',
        display:'flex',
        alignItems:'center',
        [theme.breakpoints.down('sm')]:{
            height:'350px',
            flexDirection:'column'
        }
    },
    bestmobile:{
        width:'100%',
        display:'flex',
        alignItems:'center',
        flexDirection:'column',

    },
    itemssmobile:{
        width:'23%',
        height:'100%',
        display:'flex',
        alignItems:'center',
        flexDirection:'column',
        marginRight:'5px',
        boxShadow: ' rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px',
        marginRight:'20px',
        [theme.breakpoints.down('sm')]:{
            width:'50%',
            marginTop:'30px'
        }
    },
}))